### ISSUE TITLE
test on my own dataset

### ISSUE THREAD

**Issue by muqiu791** [MCG-NJU/MixFormer#105]
您好，非常感谢您的工作！我对您的工作很感兴趣，想要测试我自己的数据集时遇到了问题。

我在单卡2080Ti上执行命令  **bash tracking/test_mixformer_cvt.sh**。 使用MixFormer-1k测试我的Anti-UAV数据集
`python tracking/test.py mixformer_cvt_online baseline_1k --dataset anti_uav_train --threads 1 --num_gpus 1 --params__model mixformer_cvt_online_1k.pth.tar --params__search_area_scale 4.55`
使用的模型是的mixformer_online_1k.pth.tar，**这里我把模型文件名改成了 mixformer_cvt_online_1k.pth.tar**。

运行后出现Warning报错 **Warning: Pretrained CVT weights are not loaded** ，但在我的数据集目录下能生成对应的Bbox坐标和time的txt文件（第一个序列没成功生成），而 RESULTS_PATH 和 RESULTS_PLOT_PATH 没有文件。

请问这样的结果合理吗，得到的结果是否可认为是MixFormer-1k模型的结果？

运行结果如下：

> {'model': 'mixformer_cvt_online_1k.pth.tar', 'search_area_scale': 4.55, 'max_score_decay': 1.0, 'vis_attn': 0}
tracking/../lib/test/evaluation/anti_uavdataset.py:29: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  ground_truth_rect = np.array(gt_rect_values)
test config:  {'MODEL': {'HEAD_TYPE': 'CORNER', 'HIDDEN_DIM': 384, '.....
}}}
search_area_scale: 4.55
Evaluating    1 trackers on    50 sequences
Tracker: mixformer_cvt_online baseline_1k None ,  Sequence: /root/autodl-tmp/MixFormer/data/Anti-UAV/train/20190925_101846_1_1
Warning: Pretrained CVT weights are not loaded
head channel: 384
Online size is:  3
Update interval is:  200
max score decay = 1.0
can't multiply sequence by non-int of type 'list'
Tracker: mixformer_cvt_online baseline_1k None ,  Sequence: /root/autodl-tmp/MixFormer/data/Anti-UAV/train/20190925_101846_1_2
Warning: Pretrained CVT weights are not loaded
head channel: 384
Online size is:  3
Update interval is:  200
max score decay = 1.0
Using /root/.cache/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module _prroi_pooling...
FPS: 23.317997237067637
Tracker: mixformer_cvt_online baseline_1k None ,  Sequence: /root/autodl-tmp/MixFormer/data/Anti-UAV/train/20190925_101846_1_3
Warning: Pretrained CVT weights are not loaded
head channel: 384
Online size is:  3
Update interval is:  200
....

期待您的答复!

**Comment by yutaocui** [comment]
hi，感谢对我们工作的关注，这个warning可以忽略，其实是可以修改一下代码就不显示了，我们后续更新该repo的话会改一下这个问题，详见：https://github.com/MCG-NJU/MixFormer/blob/8b87088f45af02c614a277176c63181261e93de3/lib/models/mixformer_cvt/mixformer_online.py#L842
你只需要把合适的测试跟踪模型路径load对就可以了

**Comment by muqiu791** [comment]
了解了，我的模型是按照建议放在models文件夹下的，路径是正确的，只是改了模型的名称，因为我百度云下载是mixformer_online_1k.pth.tar，我理解为这个就是mixformer_cvt_online_1k.pth.tar模型。
非常感谢您的答复！
