### ISSUE TITLE
Con not compile Precise RoI Pooling library

### ISSUE THREAD

**Issue by wyanb** [MCG-NJU/MixFormer#11]
{'model': 'mixformer_online_22k.pth.tar', 'update_interval': 25, 'online_sizes': 3, 'search_area_scale': 4.5, 'max_score_decay': 1.0, 'vis_attn': 0}
test config:  {'MODEL': {'HEAD_TYPE': 'CORNER', 'HIDDEN_DIM': 384, 'NUM_OBJECT_QUERIES': 1, 'POSITION_EMBEDDING': 'sine', 'PREDICT_MASK': False, 'BACKBONE': {'PRETRAINED': True, 'PRETRAINED_PATH': '', 'INIT': 'trunc_norm', 'NUM_STAGES': 3, 'PATCH_SIZE': [7, 3, 3], 'PATCH_STRIDE': [4, 2, 2], 'PATCH_PADDING': [2, 1, 1], 'DIM_EMBED': [64, 192, 384], 'NUM_HEADS': [1, 3, 6], 'DEPTH': [1, 4, 16], 'MLP_RATIO': [4.0, 4.0, 4.0], 'ATTN_DROP_RATE': [0.0, 0.0, 0.0], 'DROP_RATE': [0.0, 0.0, 0.0], 'DROP_PATH_RATE': [0.0, 0.0, 0.1], 'QKV_BIAS': [True, True, True], 'CLS_TOKEN': [False, False, False], 'POS_EMBED': [False, False, False], 'QKV_PROJ_METHOD': ['dw_bn', 'dw_bn', 'dw_bn'], 'KERNEL_QKV': [3, 3, 3], 'PADDING_KV': [1, 1, 1], 'STRIDE_KV': [2, 2, 2], 'PADDING_Q': [1, 1, 1], 'STRIDE_Q': [1, 1, 1], 'FREEZE_BN': True}, 'PRETRAINED_STAGE1': True, 'NLAYER_HEAD': 3, 'HEAD_FREEZE_BN': True}, 'TRAIN': {'TRAIN_SCORE': True, 'SCORE_WEIGHT': 1.0, 'LR': 0.0001, 'WEIGHT_DECAY': 0.0001, 'EPOCH': 30, 'LR_DROP_EPOCH': 20, 'BATCH_SIZE': 32, 'NUM_WORKER': 8, 'OPTIMIZER': 'ADAMW', 'BACKBONE_MULTIPLIER': 0.1, 'GIOU_WEIGHT': 2.0, 'L1_WEIGHT': 5.0, 'DEEP_SUPERVISION': False, 'FREEZE_STAGE0': False, 'PRINT_INTERVAL': 50, 'VAL_EPOCH_INTERVAL': 5, 'GRAD_CLIP_NORM': 0.1, 'SCHEDULER': {'TYPE': 'step', 'DECAY_RATE': 0.1}}, 'DATA': {'SAMPLER_MODE': 'trident_pro', 'MEAN': [0.485, 0.456, 0.406], 'STD': [0.229, 0.224, 0.225], 'MAX_SAMPLE_INTERVAL': [200], 'TRAIN': {'DATASETS_NAME': ['GOT10K_vottrain', 'LASOT', 'COCO17', 'TRACKINGNET'], 'DATASETS_RATIO': [1, 1, 1, 1], 'SAMPLE_PER_EPOCH': 60000}, 'VAL': {'DATASETS_NAME': ['GOT10K_votval'], 'DATASETS_RATIO': [1], 'SAMPLE_PER_EPOCH': 10000}, 'SEARCH': {'SIZE': 320, 'FACTOR': 5.0, 'CENTER_JITTER': 4.5, 'SCALE_JITTER': 0.5}, 'TEMPLATE': {'SIZE': 128, 'FACTOR': 2.0, 'NUMBER': 2, 'CENTER_JITTER': 0, 'SCALE_JITTER': 0}}, 'TEST': {'TEMPLATE_FACTOR': 2.0, 'TEMPLATE_SIZE': 128, 'SEARCH_FACTOR': 5.0, 'SEARCH_SIZE': 320, 'EPOCH': 40, 'UPDATE_INTERVALS': {'LASOT': [200], 'GOT10K_TEST': [10], 'TRACKINGNET': [25], 'VOT20': [10], 'VOT20LT': [200], 'OTB': [6], 'UAV': [200]}, 'ONLINE_SIZES': {'LASOT': [2], 'GOT10K_TEST': [2], 'TRACKINGNET': [1], 'VOT20': [5], 'VOT20LT': [3], 'OTB': [3], 'UAV': [1]}}}
search_area_scale: 4.5
Warning: Pretrained CVT weights are not loaded
head channel: 384
Online size is:  3
Update interval is:  25
max score decay = 1.0
Using C:\Users\210\AppData\Local\torch_extensions\torch_extensions\Cache as PyTorch extensions root...
C:\Users\210\anaconda3\envs\mixformer1\lib\site-packages\torch\utils\cpp_extension.py:274: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\210\AppData\Local\torch_extensions\torch_extensions\Cache\_prroi_pooling\build.ninja...
Building extension module _prroi_pooling...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
Loading extension module _prroi_pooling...
Traceback (most recent call last):
  File "tracking\..\external\PreciseRoIPooling\pytorch\prroi_pool\functional.py", line 33, in _import_prroi_pooling
    verbose=True
  File "C:\Users\210\anaconda3\envs\mixformer1\lib\site-packages\torch\utils\cpp_extension.py", line 980, in load
    keep_intermediates=keep_intermediates)
  File "C:\Users\210\anaconda3\envs\mixformer1\lib\site-packages\torch\utils\cpp_extension.py", line 1196, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\210\anaconda3\envs\mixformer1\lib\site-packages\torch\utils\cpp_extension.py", line 1543, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "C:\Users\210\anaconda3\envs\mixformer1\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_prroi_pooling'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tracking/video_demo.py", line 53, in <module>
    main()
  File "tracking/video_demo.py", line 49, in main
    args.save_results, tracker_params=tracker_params)
  File "tracking/video_demo.py", line 21, in run_video
    tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=debug, save_results=save_results)
  File "tracking\..\lib\test\evaluation\tracker.py", line 228, in run_video
    out = tracker.track(frame)
  File "tracking\..\lib\test\tracker\mixformer_online.py", line 135, in track
    out_dict, _ = self.network.forward_test(search, run_score_head=True)
  File "tracking\..\lib\models\mixformer\mixformer_online.py", line 850, in forward_test
    out, outputs_coord_new = self.forward_head(search, template, run_score_head, gt_bboxes)
  File "tracking\..\lib\models\mixformer\mixformer_online.py", line 875, in forward_head
    out_dict.update({'pred_scores': self.score_branch(search, template, gt_bboxes).view(-1)})
  File "C:\Users\210\anaconda3\envs\mixformer1\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "tracking\..\lib\models\mixformer\mixformer_online.py", line 798, in forward
    search_box_feat = rearrange(self.search_prroipool(search_feat, target_roi), 'b c h w -> b (h w) c')
  File "C:\Users\210\anaconda3\envs\mixformer1\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "tracking\..\external\PreciseRoIPooling\pytorch\prroi_pool\prroi_pool.py", line 28, in forward
    return prroi_pool2d(features, rois, self.pooled_height, self.pooled_width, self.spatial_scale)
  File "tracking\..\external\PreciseRoIPooling\pytorch\prroi_pool\functional.py", line 44, in forward
    _prroi_pooling = _import_prroi_pooling()
  File "tracking\..\external\PreciseRoIPooling\pytorch\prroi_pool\functional.py", line 36, in _import_prroi_pooling
    raise ImportError('Can not compile Precise RoI Pooling library.')
ImportError: Can not compile Precise RoI Pooling library.

Please help me! Thanks very much

**Comment by yutaocui** [comment]
Maybe you can delete the directory 'C:\Users\210\AppData\Local\torch_extensions\torch_extensions\Cache' and then have a try.

**Comment by wyanb** [comment]
> Maybe you can delete the directory 'C:\Users\210\AppData\Local\torch_extensions\torch_extensions\Cache' and then have a try.

Thanks for your reply, but this directory cannot be deleted. Once run, it is automatically generated again. And error as above.

**Comment by wyanb** [comment]
> Maybe you can delete the directory 'C:\Users\210\AppData\Local\torch_extensions\torch_extensions\Cache' and then have a try.

Thank you for your reply in spite of your busy schedule.
I installed ninja. 
When I uninstalled it using 'pip uninstall ninja', the error is the same as above. 
Back to the complication problem, which feels like a ghost on the wall.

**Comment by yutaocui** [comment]
> > Maybe you can delete the directory 'C:\Users\210\AppData\Local\torch_extensions\torch_extensions\Cache' and then have a try.
> 
> Thank you for your reply in spite of your busy schedule. I installed ninja. When I uninstalled it using 'pip uninstall ninja', the error is the same as above. Back to the complication problem, which feels like a ghost on the wall.

Your can refer to issues in original PreciseROIPooling repo (https://github.com/vacancy/PreciseRoIPooling/issues/34#issue-479599978) or issues in pytracking (https://github.com/visionml/pytracking).
