### ISSUE TITLE
vot2020

### ISSUE THREAD

**Issue by xin858466707** [MCG-NJU/MixFormer#12]
After configuring according to the readme, I want to test vote2020, but ''Unable to connect to tracker'' appears, how can I solve it?

**Comment by jcaha** [comment]
Could you provide more information? Logs in vot workspace or error reporting in terminal will be helpful.

**Comment by xin858466707** [comment]
![image](https://user-images.githubusercontent.com/84892268/162445994-b7f16c63-911f-4760-b33c-8a37ced443ae.png)
After installing ninja and PreciseRoIPooling according to the tutorial, we encountered such a problem when we tested VOT2020 (mask). Is there any other compilation for ninja and PreciseRoIPooling after installation?

**Comment by jcaha** [comment]
The compilation uses the command "which" in shell. It seems that your os has not installed "which" tool. You may refer this issue [https://github.com/open-mmlab/mmdetection/issues/398](url)

**Comment by 858949416** [comment]
> ![image](https://user-images.githubusercontent.com/84892268/162445994-b7f16c63-911f-4760-b33c-8a37ced443ae.png) After installing ninja and PreciseRoIPooling according to the tutorial, we encountered such a problem when we tested VOT2020 (mask). Is there any other compilation for ninja and PreciseRoIPooling after installation?
Have you solved it yet? I have also encountered the same problem and I hope you can help me

**Comment by 858949416** [comment]
> The compilation uses the command "which" in shell. It seems that your os has not installed "which" tool. You may refer this issue [https://github.com/open-mmlab/mmdetection/issues/398](url)

I have also encountered the same problem and I hope you can help me
