### ISSUE TITLE
about mutil-template test

### ISSUE THREAD

**Issue by davidyang180** [MCG-NJU/MixFormer#13]
Hello! I found that in the multi-templates test, the test strategy is not the same as the test strategy of the two-templates. The template and the search region are separately calculated for attention, which is different from the training strategy, the k and v values in the MAM module are operated by concat. will this make any difference?

**Comment by yutaocui** [comment]
In fact, both the multi-templates test and training are the same, since we use an **asymmetric** mixed attention (https://github.com/MCG-NJU/MixFormer/blob/main/lib/models/mixformer/mixformer_online.py#L257).
