### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by laisimiao** [MCG-NJU/MixFormer#15]
In line751, it should be named **online_template** not template, or just am I misunderstanding?
https://github.com/MCG-NJU/MixFormer/blob/0c2663d3afbce0da138d5b42bc7f28667d077ba3/lib/models/mixformer/mixformer.py#L746-L756

**Comment by yutaocui** [comment]
Yes, that's a typo and we have corrected it (However, it has no effect on the training process). Thanks for your reminder.

**Comment by laisimiao** [comment]
Not correct in github?
Sorry for a question (I have not read all codes), why in training phase, we crop two templates and split them as input of model?

**Comment by yutaocui** [comment]
> Not correct in github?
> Sorry for a question (I have not read all codes), why in training phase, we crop two templates and split them as input of model?

In training phase, we input two templates cropped from **different frames** to align with the multiple templates mechanism in online test process.

**Comment by laisimiao** [comment]
Got it. Thanks.

**Comment by laisimiao** [comment]
Actually, it has another two similar places:
https://github.com/MCG-NJU/MixFormer/blob/1caf028003fb54e816b43bfacfa9f39be4f8f134/lib/models/mixformer/mixformer_online.py#L863-L864
and
https://github.com/MCG-NJU/MixFormer/blob/51e46aea6379a71d55e3d4aa5246e182dbd431d6/lib/models/mixformer/mixformer.py#L770-L771

**Comment by yutaocui** [comment]
Thx. We have updated the repo.
