### ISSUE TITLE
Did you freeze the backbone when training SPM?

### ISSUE THREAD

**Issue by Becomebright** [MCG-NJU/MixFormer#22]
Hi, did you freeze the backbone when training SPM? If so, could you please point out the implementation code?

**Comment by yutaocui** [comment]
Yes. You can refer to:
https://github.com/MCG-NJU/MixFormer/blob/90a6a9c9a9c874f56904796bab1ddf158948d4e3/lib/train/base_functions.py#L154-L165

**Comment by Becomebright** [comment]
Thanks a lot!
