### ISSUE TITLE
Do you get stuck on the first dataset when you run it? Evaluating 1 trackers on 1 sequences Tracker: mixformer_online baseline None , Sequence: Basketball Warning: Pretrained CVT weights are not loaded head channel: 384 It's just like this, it's been running all night

### ISSUE THREAD

**Issue by 123wfl** [MCG-NJU/MixFormer#23]
When I tested it, it was stuck below, and it was still the same after running for a night. How can I solve it?
Evaluating 1 trackers on 1 sequences
Tracker: mixformer_online baseline None , Sequence: Basketball
Warning: Pretrained CVT weights are not loaded
head channel: 384

**Comment by 123wfl** [comment]
nothing works

**Comment by chansongoal** [comment]
Hi, have you fixed this problem? I encountered the same problem and have no idea why could this happen. Appreciate it if you have any suggestions.
