### ISSUE TITLE
Can I get guideline path?

### ISSUE THREAD

**Issue by jjuun0** [MCG-NJU/MixFormer#29]
I want to test model, but i got this error

RuntimeError: YOU HAVE NOT SETUP YOUR local.py!!!

Only i want to test pretrained model, this local.py path need?

**Comment by jcaha** [comment]
Did you run this command?
```
python tracking/create_default_local_file.py --workspace_dir . --data_dir ./data --save_dir 
```
And if you want to test on VOT2020, you may refer [external/AR/README.md](https://github.com/MCG-NJU/MixFormer/blob/main/external/AR/README.md) and run the following command:
```
cd external/AR/
python -c "from pytracking.evaluation.environment import create_default_local_file; create_default_local_file()"
python -c "from ltr.admin.environment import create_default_local_file; create_default_local_file()"
```

**Comment by JAYCHOU2020** [comment]
> I want to test model, but i got this error
> 
> RuntimeError: YOU HAVE NOT SETUP YOUR local.py!!!
> 
> Only i want to test pretrained model, this local.py path need?

I meet the same problem
