### ISSUE TITLE
VOT2020

### ISSUE THREAD

**Issue by xin858466707** [MCG-NJU/MixFormer#30]
In the results of VOT2020, what does unsupervised mean?
![QQ图片20220518101002](https://user-images.githubusercontent.com/84892268/168942739-ef142d69-2f92-45d3-8e54-df43b25153b4.png)

**Comment by jcaha** [comment]
Unsupervised AUC is the no-reset average overlap AO employed in OTB dataset. Trackers are initialized by the target bbox in the first frame, and will not be reset if the target is lost.
