### ISSUE TITLE
"trident_pro" sample mode

### ISSUE THREAD

**Issue by kongbia** [MCG-NJU/MixFormer#31]
Hi, why the `template_frame_ids_extra` could be invisible (line 316) when the sample mode is set to `"trident_pro"`?

[](url)https://github.com/MCG-NJU/MixFormer/blob/90a6a9c9a9c874f56904796bab1ddf158948d4e3/lib/train/data/sampler.py#L300-L325

**Comment by wanglimin** [comment]
In fact, we use the same sampling strategy as STARK. `template_frame_ids_extra` represents for dynamic templates. `allow_invisible` means the dynamic templates can be invisible samples (i.e., `out of view` or `occlusion`). In this way, we add some noise to the dynamic templates which aligns with online tracking.
