### ISSUE TITLE
how to use this project to run the demo?

### ISSUE THREAD

**Issue by jigongbao** [MCG-NJU/MixFormer#4]
i have some my own videos and i hope to run the demo to see the results, but i don`t know how to use

**Comment by yutaocui** [comment]
we will add this function soon.

**Comment by yutaocui** [comment]
> i have some my own videos and i hope to run the demo to see the results, but i don`t know how to use

We have updated the repo. Now you can view tracking/run_video_demo.sh to set the proper path for your own video.

**Comment by jigongbao** [comment]
thanks!!!

**Comment by yutaocui** [comment]
You don't need to set the project path in the local.py. However the dataset path is not required.
