### ISSUE TITLE
您好，作者。请问您论文中的热力图是如何制作的，有没有开源代码。

### ISSUE THREAD

**Issue by Quan-w** [MCG-NJU/MixFormer#44]

**Comment by yutaocui** [comment]
我们提供了代码，可以参考：https://github.com/MCG-NJU/MixFormer/blob/90a6a9c9a9c874f56904796bab1ddf158948d4e3/lib/test/tracker/mixformer_online.py#L112

**Comment by Quan-w** [comment]
好的谢谢
