### ISSUE TITLE
输入图像的问题

### ISSUE THREAD

**Issue by congjianting** [MCG-NJU/MixFormer#47]
@jcaha @yutaocui 你们好,

mixformer的输入图像们在训练和推理过程中是个什么情况?

我看论文中提到需要2个模板图和1个搜索图,  这个是什么原理呢?
我的工作这里只有1个模板图和1个搜索图, 能适用于mixformer吗?

C. Training Details
We propose a 320x320 search region plus two 128x128 input
images to make a fair comparison with prevailing trackers (e.g.,
Siamese-based trackers, STARK and TransT).

**Comment by yutaocui** [comment]
训练时用两个模板是为了模拟inference时的online，只有一个也是没问题的
