### ISSUE TITLE
 How your model find the output belongs to search region for prediction?

### ISSUE THREAD

**Issue by jananithangavel** [MCG-NJU/MixFormer#48]

**Comment by yutaocui** [comment]
I guess you mean how the model differentiates the search region from the targets?
For mixformer architecture with convolution implicitly encoding the positional embeddings, it can learn the positional differentiations between the two ones. 
For MixViT with substituting the backbone with ViT, we have experimented three different kinds of positional embeddings for search and targets respectively and obtained similar performance. It indicates that additional pos. emb. for differentiating the two ones are unnecessary.
