### ISSUE TITLE
What's the difference between experiments/mixformer & mixformer_online?

### ISSUE THREAD

**Issue by Nirvana9808** [MCG-NJU/MixFormer#49]
Hello! 
GOT-10k, I used experiment/mixformer/baseline_got.yaml for training and mixformer_online_22k_got.pth.tar for pre-training model, but the training result were not available for testing. There were no results after testing, and no errors were reported during testing. It looks like we didn't get the yaml file. My test statement is :
python tracking/test.py mixformer_online baseline_got --dataset_name got10k_test --threads 12 --num_gpus 2 --params_model 'model absolute path' --params__search_area+scale 4.55.

And then used experiment/mixformer_online/baseline_got.yaml. Repeat this and it works, but the results don't seem to be right. In result.txt , four our numbers, the last two are always 10,10. This was not the case when I used the pre-trained model directly for testing.

Looking forward to your reply.

**Comment by Nirvana9808** [comment]
作者您好，谢谢您的回复。mixformer_online是最后训练头得到的模型吧？可以提供一下您的stage1阶段的预训练模型吗？我想在您预训练模型的基础上在进行训练。现有的预训练模型都是经过online训练过的，无法作为stage1的预训练模型使用。谢谢您的帮助，期待您的回复。





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MCG-NJU/MixFormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月2日(星期四) 晚上11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MCG-NJU/MixFormer] What's the difference between experiments/mixformer &amp; mixformer_online? (Issue #49)





 
Hi, MixFormer_online is the online temporal version, which exists a score prediction module to select online templates. While MixFormer.py only uses the first template.

**Comment by yutaocui** [comment]
mixformer_online是在mixformer训练完之后，再freeze掉，只训练score prediction module（SPM）。所以如果需要stage1模型，只需要不load SPM的参数就可以了

**Comment by Nirvana9808** [comment]
问题已解决，谢谢您的答复。祝您科研顺利谢谢。





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MCG-NJU/MixFormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月6日(星期一) 下午4:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MCG-NJU/MixFormer] What's the difference between experiments/mixformer &amp; mixformer_online? (Issue #49)





 
mixformer_online是在mixformer训练完之后，再freeze掉，只训练score prediction module（SPM）。所以如果需要stage1模型，只需要不load SPM的参数就可以了

**Comment by yutaocui** [comment]
不客气～
