### ISSUE TITLE
Training log of training SPM

### ISSUE THREAD

**Issue by EavanLi** [MCG-NJU/MixFormer#50]
Could you show the training log of stage 2 （i.e., training SPM）?
I want to see if my training process is normal as a reference. Thank you.

**Comment by yutaocui** [comment]
Hi, you can find the logs including mixformer and mixformer_online_module training logs at https://drive.google.com/drive/folders/1LdV0QWVbxVG6NFpmzxVSD67IQmStPRJw?usp=share_link.

**Comment by LY-1** [comment]
作者您好，我在got-10k数据集上训练时碰到一些问题。我训练并不是直接运行的sh文件，而是输入指令运行的。在训练SPM时，我发现log信息中并没有输出giou、l1损失以及IoU信息，最后我在test的时候，发现输出的宽高都是10。请问这种情况我应该怎么解决？
