### ISSUE TITLE
跟踪目标的空间位移较大时的算法精度问题

### ISSUE THREAD

**Issue by congjianting** [MCG-NJU/MixFormer#55]
@wanglimin @jcaha @yutaocui 

各位作者老师, 好,

实际工作中通常遇到视频抽帧间隔较大的情况, 这样导致跟踪目标可能会出现在相邻图像帧之间的空间位移较大,

请问这种会对mixformer产生精度影响吗?  如果有影响, 请问模型训练中有哪些参数可以调节来适应这种情况?

期待各位老师的回复, 谢谢.
祝好.

**Comment by yutaocui** [comment]
你好，这个是会有影响的，建议通过调一下search_area_factor，一般来说位移大的话需要调大一些，最好是基于你的数据集重新训
