### ISSUE TITLE
 test my pretrained model

### ISSUE THREAD

**Issue by JAYCHOU2020** [MCG-NJU/MixFormer#56]
使用以下语句运行来测试自己训练的模型 ：python tracking/test.py mixformer_online baseline --dataset lasot --threads 32 --num_gpus 2 --params__model MixFormer_ep0180.pth.tar  --params__search_area_scale 4.55。
报错：     'Then try to run again.'.format(env_file))   RuntimeError: YOU HAVE NOT SETUP YOUR local.py!!!
在其他issues 中看到 
![image](https://user-images.githubusercontent.com/62323435/202073957-269b0535-a5a1-4b0a-beab-7467e445e38f.png)
运行后不在报  local.py 的错误 
但是出现以下错误
![image](https://user-images.githubusercontent.com/62323435/202077490-8fcbd503-32be-413f-9f7c-5fd3765a1f83.png)

想知道如何才能正确运行test.py来测试自己训练的模型呢

**Comment by yutaocui** [comment]
需要在local.py中设置一下各种路径

**Comment by JAYCHOU2020** [comment]
> 



> 需要在local.py中设置一下各种路径

![image](https://user-images.githubusercontent.com/62323435/202096770-c7be116b-9ca6-4450-b1d0-a621baf01b6a.png)
大多已经设置 过了，想问一下davis_dir 和network_path 指的的什么呢

**Comment by JAYCHOU2020** [comment]
> 需要在local.py中设置一下各种路径

![image](https://user-images.githubusercontent.com/62323435/202098120-efd14557-11be-4444-9b2d-efec3359aeae.png)

**Comment by yutaocui** [comment]
这两个目前没用到，一个是davis数据集路径，另一个没用。
你报的错是载入的模型没有score prediction模块，应该是你自己训练的没有是不包含online模块的吧？那你改一下设置，不要用mixformer_online，用mixformer的配置文件和tracker等

**Comment by JAYCHOU2020** [comment]
> 

是的是的我训练的不包括online ，好的我去改一下谢谢谢谢

**Comment by yutaocui** [comment]
已解决

**Comment by JAYCHOU2020** [comment]
> 不客气

我还想再问下，再训练mixformer_online是需要加载先前训练的mixforemer的模型吧？

**Comment by JAYCHOU2020** [comment]
> 不客气

我还想再问下，再训练mixformer_online还需要加载CVT模型吗还是只需要加载mixformer的模型
