### ISSUE TITLE
训练过程中的目标丢失数据的问题

### ISSUE THREAD

**Issue by congjianting** [MCG-NJU/MixFormer#58]
作者老师,你好,

训练过程中, 如果一个训练数据文件夹中某几个图片出现目标丢失, 想问下这几张丢失目标的图片还参与训练吗?

以got-10k为例, 我看dataset中存在如下处理, 

    def get_sequence_info(self, seq_id):
        seq_path = self._get_sequence_path(seq_id)
        bbox = self._read_bb_anno(seq_path)

        valid = (bbox[:, 2] > 0) & (bbox[:, 3] > 0)
        visible, visible_ratio = self._read_target_visible(seq_path)
        visible = visible & valid.byte()

        return {'bbox': bbox, 'valid': valid, 'visible': visible, 'visible_ratio': visible_ratio}

**Comment by yutaocui** [comment]
你好，这种是不参与训练的
