### ISSUE TITLE
Has anyone tested on the UAVDT dataset

### ISSUE THREAD

**Issue by Old-detective** [MCG-NJU/MixFormer#62]

**Comment by JAYCHOU2020** [comment]
> _No description provided._

你在uav123上测试过吗？
![image](https://user-images.githubusercontent.com/62323435/205280162-1a500e27-f221-4119-93be-c8fe67c5cca9.png)
这个错误是因为什么呢

**Comment by congjianting** [comment]
试试[200]

**Comment by Old-detective** [comment]
> > _No description provided._
> 
> 你在uav123上测试过吗？ ![image](https://user-images.githubusercontent.com/62323435/205280162-1a500e27-f221-4119-93be-c8fe67c5cca9.png) 这个错误是因为什么呢

测试过。但是没有遇到过你这个问题
