### ISSUE TITLE
mixformer推理阶段的search图没有目标的处理情况

### ISSUE THREAD

**Issue by congjianting** [MCG-NJU/MixFormer#63]
@yutaocui 

崔老师, 你好,

mixformer离线模型推理时, 如果template图的目标不在search图时, 也会推理出一个corner box, 想问下如果判断推理出的corner box的真伪?

**Comment by yutaocui** [comment]
我们的方法没有进行特殊的处理，所以可以通过一些后处理或其他trick提升效果
