### ISSUE TITLE
Mixformer不能训练自己想训练的数据集吗？

### ISSUE THREAD

**Issue by Old-detective** [MCG-NJU/MixFormer#64]
怎么找不到相关设置？比如我想训练UAVDT数据集，该怎么配置？有没有大佬指导一下

**Comment by HJ1722** [comment]
請問你有解決這個問題了嗎？

**Comment by yutaocui** [comment]
可以训练自己的数据集，需要参考https://github.com/MCG-NJU/MixFormer/tree/main/lib/train/dataset添加自己的数据集
