### ISSUE TITLE
Training requirement

### ISSUE THREAD

**Issue by CarlHuangNuc** [MCG-NJU/MixFormer#73]
Hi,

     Could you share some GPU information and Length of training time ？ I try to reproduce your paper , but found this paper have a lot of dependence on High level training platform (A100 or more than A100).

**Comment by yutaocui** [comment]
For MixViT-B (ViT-B or ConvMAE-B) training, we use 8 2080ti or Tesla v100 GPUs and cost about 50+ hours.
For MixViT-L (ViT-L or ConvMAE-L), 8 Tesla v100 or RTX 8000 GPUs are used for training around 4+ days.
In fact, maybe 300 epochs instead of 500 epochs in our paper are enough for training.

**Comment by CarlHuangNuc** [comment]
Thanks,
