### ISSUE TITLE
跑got10k验证集时出现AttributeError

### ISSUE THREAD

**Issue by Coronal-yup** [MCG-NJU/MixFormer#77]
您好，首先非常感谢您的工作！我在跑got10k验证集时出现'MixFormerOnline' object has no attribute 'online_sizes'，暂时不知道该如何解决？

**Comment by songtianhui** [comment]
可以提供一下运行的命令和具体报错message

**Comment by Coronal-yup** [comment]
运行命令：python tracking/test.py mixformer_vit_online baseline_large --dataset got10k_val --threads 32 --num_gpus 2 --params__model mixformer_vit_large_online.pth.tar
具体报错信息：每个序列都会报错一次'MixFormerOnline' object has no attribute 'online_sizes'
以上是问题的详细描述，十分感谢您！

**Comment by songtianhui** [comment]
因为你测试的 got10k_val，got10k_val 是用在验证而不是测试中的，如果要测试应该使用 got10k_test。

**Comment by songtianhui** [comment]
非online的就是online模型去掉score module部分，权重是完全一样的。

**Comment by Coronal-yup** [comment]
好的，我们已经有了idea想要在没有x_ot的版本上进行修改构造一个新模型，非常感谢您的工作，希望有问题能再与您交流。
