### ISSUE TITLE
test时遇到的local文件的问题

### ISSUE THREAD

**Issue by FFFionana** [MCG-NJU/MixFormer#78]
![image](https://user-images.githubusercontent.com/120310428/227777617-c23b6884-65a9-4c8f-b627-d99d9c826299.png)
您好，有一个小问题想请教一下，在第一次运行生成local文件后进行了设置，再次运行依然出现了这个问题，请问是为什么呀？

**Comment by songtianhui** [comment]
有运行命令 `python tracking/create_default_local_file.py --workspace_dir . --data_dir ./data --save_dir .` 吗

**Comment by FFFionana** [comment]
您的意思是必须先运行以上这行代码，不能在生成了local之后再进行设置么

**Comment by FFFionana** [comment]
您好，我按照您说的运行了代码，再次尝试test时依然出现了如上问题

**Comment by FFFionana** [comment]
感谢您的回复，是默认导入local的地址有点问题，已经解决了，十分感谢
