### ISSUE TITLE
关于代码阅读的一些疑惑

### ISSUE THREAD

**Issue by rainbowsea123** [MCG-NJU/MixFormer#83]
您好，在我阅读代码的过程中，由于个人的代码理解能力有限，没有找到训练用模型中根据Score进行模板更新的部分代码在哪里和实现的方式，仅找到了测试模型中的更新代码。根据论文中的描述，似乎在训练时没有进行模板更新对吗？如果有的话，能否请您指点一下？

**Comment by yutaocui** [comment]
我们是采用两阶段训练方式的，第二阶段就是score分支的训练，具体可以参考 https://github.com/MCG-NJU/MixFormer/blob/55324784e6e46140e46fba879bf38902d4558d25/tracking/train_mixformer_convmae.sh#L9

**Comment by rainbowsea123** [comment]
好的，谢谢
