### ISSUE TITLE
About training logs

### ISSUE THREAD

**Issue by davidyang180** [MCG-NJU/MixFormer#9]
Hello!This is an excellent work. I don't see the training log provided in the model zoo. Can you provide the training log of the reproduced results later? like stark

**Comment by yutaocui** [comment]
[mixformer_baseline.log](https://github.com/MCG-NJU/MixFormer/files/8382157/mixformer_baseline.log)
Thanks for your attention. The attached file is the log of our initial training code which you can refer to (batch size is 8 on 8 2080Ti GPUs).
