### ISSUE TITLE
Use pretrained model on CPU

### ISSUE THREAD

**Issue by ThanhLong2906** [MCG-NJU/MixFormer#94]
Hi everyone, i want use Mixformer's pretrained model for tracking my own video but i only have CPU, how to do that ?

**Comment by yutaocui** [comment]
In this case, I recommend you try [MixFormerV2](https://github.com/MCG-NJU/MixFormerV2).

**Comment by ThanhLong2906** [comment]
i did it, thank u so muchh @yutaocui

**Comment by tommywu1001** [comment]
How do you use the CPU test? I see only single gpu and multi-gpu in the code.
